# Generated by Django 3.1.3 on 2020-12-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20201202_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.IntegerField()),
                ('chairs', models.IntegerField()),
            ],
        ),
    ]
