# Generated by Django 3.1.3 on 2020-12-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='作者')),
                ('age', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'author',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='书籍名称')),
                ('pages', models.IntegerField(verbose_name='书籍页数')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='书籍价格')),
                ('rating', models.FloatField(verbose_name='书籍评分')),
                ('pubdate', models.DateField(verbose_name='发布日期')),
                ('authors', models.ManyToManyField(to='article.Author')),
            ],
            options={
                'db_table': 'book',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='发布者')),
            ],
            options={
                'db_table': 'publisher',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='书店名')),
                ('books', models.ManyToManyField(to='article.Book')),
            ],
            options={
                'db_table': 'store',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publishers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.publisher'),
        ),
    ]
